language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql

services:
  - redis-server

install:
  - sh -c "if [ '$DB' = 'mariadb' ]; then travis/setup-mariadb.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then travis/setup-php-extensions.sh; fi"
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then travis/setup-webserver.sh; fi"
  - cd phpBB
  - php ../composer.phar install --dev --no-interaction --prefer-source
  - cd ..

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - travis/phing-code-sniff.sh $DB $TRAVIS_PHP_VERSION
  - phpBB/vendor/bin/phpunit --configuration travis/phpunit-$DB-travis.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' -a '$TRAVIS_PULL_REQUEST' != 'false' ]; then git-tools/commit-msg-hook-range.sh origin/$TRAVIS_BRANCH..FETCH_HEAD; fi"

matrix:
  include:
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
  allow_failures:
    - php: hhvm
  fast_finish: true
